version: '3.5'

services:
  uth-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc0
    entrypoint: /bin/bash
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_AGENT_PORT}:${ACAPY_AGENT_PORT}
    environment:
      # Indy
      # Agent networking
      ACAPY_ENDPOINT: 'http://localhost:${ACAPY_AGENT_PORT}'
      ACAPY_WEBHOOK_URL: 'http://${DOCKER_GATEWAY_HOST:-localhost}:${ACAPY_WEBHOOK_PORT}/webhooks'
      ACAPY_OUTBOUND_TRANSPORT: 'http'
      ACAPY_GENESIS_URL: 'http://${DOCKER_GATEWAY_HOST:-localhost}:9000/genesis'
      # Wallet
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_WALLET_TYPE: 'indy'
      ACAPY_WALLET_NAME: 'uth-wallet'
      ACAPY_WALLET_KEY: 'secret-wallet-key'
      # Admin
      ACAPY_ADMIN_INSECURE_MODE: "true"
      # Invites
      ACAPY_INVITE_LABEL: 'UTH'
      ACAPY_AUTO_ACCEPT_REQUESTS: "true"
    command:  [
      "-c",
      " sleep 5; \
        aca-py start \
        -it http '0.0.0.0' ${ACAPY_AGENT_PORT} \
        -ot http \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT}",
    ]
    extra_hosts:
      - "localhost:host-gateway"
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-uth}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: 'uth-ssi'
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  db:
    name: 'uth-postgres'
    driver: local
