label: John
invite-label: John
wallet-name: john
endpoint:
  - http://john-agent:4002
  - http://localhost:4002
inbound-transport:
  - ['http', 0.0.0.0, 4002]
admin: [0.0.0.0, 4003]

# Transport
outbound-transport: http
webhook-url: 'http://localhost:4001/webhooks'

# Ledger
# Use Sovrin Builder Net. Become an endorser at https://selfserve.sovrin.org.
genesis-url: http://localhost:9000/genesis

# Admin
admin-insecure-mode: true

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Credentials and Presentations
preserve-exchange-records: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true

auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true

# Wallet
wallet-type: indy
wallet-key: "insecure, for use in demo only"
auto-provision: true

# Enable undelivered queue
# Important for communication with toolbox over http (as opposed to ws)
enable-undelivered-queue: true

# Catch Admin Trust Pings
monitor-ping: true
